$ heroku logs --tail
2021-04-19T19:31:35.623446+00:00 app[web.1]: self.reap_workers()
2021-04-19T19:31:35.623475+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2021-04-19T19:31:35.623859+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)     
2021-04-19T19:31:35.624648+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2021-04-19T19:31:35.624673+00:00 app[web.1]:
2021-04-19T19:31:35.624675+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2021-04-19T19:31:35.624675+00:00 app[web.1]:
2021-04-19T19:31:35.624704+00:00 app[web.1]: Traceback (most recent call last):
2021-04-19T19:31:35.624733+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2021-04-19T19:31:35.624971+00:00 app[web.1]: sys.exit(run())
2021-04-19T19:31:35.625004+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2021-04-19T19:31:35.625229+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2021-04-19T19:31:35.625257+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run
2021-04-19T19:31:35.625520+00:00 app[web.1]: super().run()
2021-04-19T19:31:35.625546+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
2021-04-19T19:31:35.632679+00:00 app[web.1]: Arbiter(self).run()
2021-04-19T19:31:35.633154+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
2021-04-19T19:31:35.633531+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2021-04-19T19:31:35.633564+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
2021-04-19T19:31:35.633901+00:00 app[web.1]: self.stop()
2021-04-19T19:31:35.635964+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 393, in stop
2021-04-19T19:31:35.636341+00:00 app[web.1]: time.sleep(0.1)
2021-04-19T19:31:35.636372+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2021-04-19T19:31:35.636637+00:00 app[web.1]: self.reap_workers()
2021-04-19T19:31:35.636670+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2021-04-19T19:31:35.637431+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)     
2021-04-19T19:31:35.637592+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2021-04-19T19:31:35.770593+00:00 heroku[web.1]: Process exited with status 1
2021-04-19T19:31:35.965449+00:00 heroku[web.1]: State changed from up to crashed
2021-04-19T19:31:35.971168+00:00 heroku[web.1]: State changed from crashed to starting
2021-04-19T19:31:44.328899+00:00 heroku[web.1]: Starting process with command `gunicorn -b :13044 
app:app`
2021-04-19T19:31:48.265421+00:00 app[web.1]: [2021-04-19 19:31:48 +0000] [4] [INFO] Starting gunicorn 20.1.0
2021-04-19T19:31:48.266613+00:00 app[web.1]: [2021-04-19 19:31:48 +0000] [4] [INFO] Listening at: 
http://0.0.0.0:13044 (4)
2021-04-19T19:31:48.266831+00:00 app[web.1]: [2021-04-19 19:31:48 +0000] [4] [INFO] Using worker: 
sync
2021-04-19T19:31:48.276228+00:00 app[web.1]: [2021-04-19 19:31:48 +0000] [7] [INFO] Booting worker with pid: 7
2021-04-19T19:31:48.289099+00:00 app[web.1]: [2021-04-19 19:31:48 +0000] [8] [INFO] Booting worker with pid: 8
2021-04-19T19:31:48.772647+00:00 heroku[web.1]: State changed from starting to up
2021-04-19T19:31:53.446297+00:00 app[web.1]: [2021-04-19 19:31:53 +0000] [7] [ERROR] Exception in 
worker process
2021-04-19T19:31:53.446327+00:00 app[web.1]: Traceback (most recent call last):
2021-04-19T19:31:53.446329+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2021-04-19T19:31:53.446330+00:00 app[web.1]: worker.init_process()
2021-04-19T19:31:53.446331+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
2021-04-19T19:31:53.446331+00:00 app[web.1]: self.load_wsgi()
2021-04-19T19:31:53.446332+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2021-04-19T19:31:53.446332+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2021-04-19T19:31:53.446333+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2021-04-19T19:31:53.446333+00:00 app[web.1]: self.callable = self.load()
2021-04-19T19:31:53.446334+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2021-04-19T19:31:53.446334+00:00 app[web.1]: return self.load_wsgiapp()
2021-04-19T19:31:53.446334+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2021-04-19T19:31:53.446335+00:00 app[web.1]: return util.import_app(self.app_uri)
2021-04-19T19:31:53.446335+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
2021-04-19T19:31:53.446335+00:00 app[web.1]: mod = importlib.import_module(module)
2021-04-19T19:31:53.446336+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2021-04-19T19:31:53.446337+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, 
level)
2021-04-19T19:31:53.446337+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2021-04-19T19:31:53.446338+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-04-19T19:31:53.446338+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2021-04-19T19:31:53.446338+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2021-04-19T19:31:53.446339+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 790, in exec_module
2021-04-19T19:31:53.446339+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-04-19T19:31:53.446339+00:00 app[web.1]: File "/app/app.py", line 7, in <module>
2021-04-19T19:31:53.446340+00:00 app[web.1]: from secrets import API_SECRET_KEY
2021-04-19T19:31:53.446340+00:00 app[web.1]: ImportError: cannot import name 'API_SECRET_KEY' from 'secrets' (/app/.heroku/python/lib/python3.9/secrets.py)
2021-04-19T19:31:53.446658+00:00 app[web.1]: [2021-04-19 19:31:53 +0000] [7] [INFO] Worker exiting (pid: 7)
2021-04-19T19:31:53.451772+00:00 app[web.1]: [2021-04-19 19:31:53 +0000] [8] [ERROR] Exception in 
worker process
2021-04-19T19:31:53.451773+00:00 app[web.1]: Traceback (most recent call last):
2021-04-19T19:31:53.451774+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2021-04-19T19:31:53.451774+00:00 app[web.1]: worker.init_process()
2021-04-19T19:31:53.451775+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
2021-04-19T19:31:53.451775+00:00 app[web.1]: self.load_wsgi()
2021-04-19T19:31:53.451776+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2021-04-19T19:31:53.451776+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2021-04-19T19:31:53.451776+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2021-04-19T19:31:53.451777+00:00 app[web.1]: self.callable = self.load()
2021-04-19T19:31:53.451777+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2021-04-19T19:31:53.451778+00:00 app[web.1]: return self.load_wsgiapp()
2021-04-19T19:31:53.451778+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2021-04-19T19:31:53.451778+00:00 app[web.1]: return util.import_app(self.app_uri)
2021-04-19T19:31:53.451779+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
2021-04-19T19:31:53.451779+00:00 app[web.1]: mod = importlib.import_module(module)
2021-04-19T19:31:53.451779+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2021-04-19T19:31:53.451780+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, 
level)
2021-04-19T19:31:53.451780+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2021-04-19T19:31:53.451781+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-04-19T19:31:53.451781+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2021-04-19T19:31:53.451782+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2021-04-19T19:31:53.451782+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 790, in exec_module
2021-04-19T19:31:53.451782+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-04-19T19:31:53.451783+00:00 app[web.1]: File "/app/app.py", line 7, in <module>
2021-04-19T19:31:53.451783+00:00 app[web.1]: from secrets import API_SECRET_KEY
2021-04-19T19:31:53.451783+00:00 app[web.1]: ImportError: cannot import name 'API_SECRET_KEY' from 'secrets' (/app/.heroku/python/lib/python3.9/secrets.py)
2021-04-19T19:31:53.472074+00:00 app[web.1]: [2021-04-19 19:31:53 +0000] [8] [INFO] Worker exiting (pid: 8)
2021-04-19T19:31:53.876501+00:00 app[web.1]: [2021-04-19 19:31:53 +0000] [4] [WARNING] Worker with pid 8 was terminated due to signal 15
2021-04-19T19:31:53.967267+00:00 app[web.1]: [2021-04-19 19:31:53 +0000] [4] [INFO] Shutting down: Master
2021-04-19T19:31:53.967462+00:00 app[web.1]: [2021-04-19 19:31:53 +0000] [4] [INFO] Reason: Worker failed to boot.
2021-04-19T19:31:54.094502+00:00 heroku[web.1]: Process exited with status 3
2021-04-19T19:31:54.223266+00:00 heroku[web.1]: State changed from up to crashed
2021-04-19T19:32:13.100819+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=virtual-memorials.herokuapp.com request_id=1aa27c2f-9f64-4c69-a369-8dd7ae4b5493 fwd="73.147.70.17" dyno= connect= service= status=503 bytes= protocol=https
2021-04-19T19:32:13.422926+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=virtual-memorials.herokuapp.com request_id=cf0b9dab-8327-4f73-8b1a-201a3eb2c4ab fwd="73.147.70.17" dyno= connect= service= status=503 bytes= protocol=https
